version: '3.8'

services:
  server:
    build: ./
    command: ./shorter-api-server.exe
    depends_on:
      - client
      - db
    environment:
      - DATABASE_URL=postgres://postgres:qwerty@db:5432/linkshorterdb
      - PORT=:8080
    ports:
      - 8081:8080

  client:
    build:
      context: .
      dockerfile: ./client.dockerfile
    command: ./shorter-api-client.exe
    environment:
      - PORT=:8080
    ports:
      - 8181:8181

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ././database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=postgres
      - POSTGRES_DB=linkshorterdb
    ports:
      - 5436:5432
