version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: ./server.dockerfile
    command: ./shorter-api-server.exe
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:qwerty@db:5432/linkshorterdb?sslmode=disable
      - PORT=:8080
    ports:
      - 8081:8080

  client:
    build:
      context: .
      dockerfile: ./client.dockerfile
    command: ./shorter-api-client.exe
    stdin_open: true
    tty: true
    depends_on:
      - server
    environment:
      - PORT=:8080

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ././database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=postgres
      - POSTGRES_DB=linkshorterdb
    ports:
      - 5436:5432
